[package]
name = "blurg"
version = "0.1.0"
authors = ["tronje <hi@tron.je>"]

[dependencies]
time = "0.1"
regex = "0.2"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
